"""
NSE Stocks Database - 500+ stocks organized by sector
"""

NSE_STOCKS = {
    "IT - Software": {
        "TCS.NS": "Tata Consultancy Services",
        "INFY.NS": "Infosys",
        "WIPRO.NS": "Wipro",
        "HCLTECH.NS": "HCL Technologies",
        "TECHM.NS": "Tech Mahindra",
        "LTIM.NS": "LTIMindtree",
        "MPHASIS.NS": "Mphasis",
        "COFORGE.NS": "Coforge",
        "PERSISTENT.NS": "Persistent Systems",
        "OFSS.NS": "Oracle Financial Services",
        "HEXAWARE.NS": "Hexaware Technologies",
        "KPITTECH.NS": "KPIT Technologies",
        "TATAELXSI.NS": "Tata Elxsi",
        "NIIT.NS": "NIIT Technologies",
        "MASTEK.NS": "Mastek",
        "SONATSOFTW.NS": "Sonata Software",
        "ZENSAR.NS": "Zensar Technologies",
        "CYIENT.NS": "Cyient",
        "BIRLASOFT.NS": "Birlasoft",
        "RATEGAIN.NS": "RateGain Travel Technologies",
        "TANLA.NS": "Tanla Platforms",
        "NEWGEN.NS": "Newgen Software",
        "INTELLECT.NS": "Intellect Design Arena",
        "FSL.NS": "Firstsource Solutions",
        "ECLERX.NS": "eClerx Services",
    },

    "Banking - Public": {
        "SBIN.NS": "State Bank of India",
        "PNB.NS": "Punjab National Bank",
        "BANKBARODA.NS": "Bank of Baroda",
        "CANBK.NS": "Canara Bank",
        "UNIONBANK.NS": "Union Bank of India",
        "INDIANB.NS": "Indian Bank",
        "BANKINDIA.NS": "Bank of India",
        "CENTRALBK.NS": "Central Bank of India",
        "IOB.NS": "Indian Overseas Bank",
        "MAHABANK.NS": "Bank of Maharashtra",
        "UCOBANK.NS": "UCO Bank",
        "PSBBANK.NS": "Punjab & Sind Bank",
        "SYNDIBANK.NS": "Syndicate Bank",
    },

    "Banking - Private": {
        "HDFCBANK.NS": "HDFC Bank",
        "ICICIBANK.NS": "ICICI Bank",
        "KOTAKBANK.NS": "Kotak Mahindra Bank",
        "AXISBANK.NS": "Axis Bank",
        "INDUSINDBK.NS": "IndusInd Bank",
        "YESBANK.NS": "Yes Bank",
        "FEDERALBNK.NS": "Federal Bank",
        "IDFCFIRSTB.NS": "IDFC First Bank",
        "BANDHANBNK.NS": "Bandhan Bank",
        "RBLBANK.NS": "RBL Bank",
        "DCBBANK.NS": "DCB Bank",
        "SOUTHBANK.NS": "South Indian Bank",
        "KTKBANK.NS": "Karnataka Bank",
        "KARNATAKA.NS": "Karnataka Bank",
        "CUB.NS": "City Union Bank",
        "TMVFINANCE.NS": "TMV Finance",
        "LAKSHVIL.NS": "Lakshmi Vilas Bank",
    },

    "NBFC & Financial Services": {
        "BAJFINANCE.NS": "Bajaj Finance",
        "BAJAJFINSV.NS": "Bajaj Finserv",
        "HDFCLIFE.NS": "HDFC Life Insurance",
        "SBILIFE.NS": "SBI Life Insurance",
        "ICICIPRULI.NS": "ICICI Prudential Life",
        "ICICIGI.NS": "ICICI Lombard General Insurance",
        "MUTHOOTFIN.NS": "Muthoot Finance",
        "CHOLAFIN.NS": "Cholamandalam Investment",
        "M&MFIN.NS": "Mahindra & Mahindra Financial",
        "LICHSGFIN.NS": "LIC Housing Finance",
        "PNBHOUSING.NS": "PNB Housing Finance",
        "MANAPPURAM.NS": "Manappuram Finance",
        "SHRIRAMFIN.NS": "Shriram Finance",
        "SUNDARMFIN.NS": "Sundaram Finance",
        "AAVAS.NS": "Aavas Financiers",
        "HOMEFIRST.NS": "Home First Finance",
        "APTUS.NS": "Aptus Value Housing Finance",
        "CREDITACC.NS": "CreditAccess Grameen",
        "SPANDANA.NS": "Spandana Sphoorty Financial",
        "UGROCAP.NS": "Ugro Capital",
    },

    "FMCG": {
        "HINDUNILVR.NS": "Hindustan Unilever",
        "ITC.NS": "ITC Limited",
        "NESTLEIND.NS": "Nestle India",
        "BRITANNIA.NS": "Britannia Industries",
        "DABUR.NS": "Dabur India",
        "MARICO.NS": "Marico",
        "GODREJCP.NS": "Godrej Consumer Products",
        "COLPAL.NS": "Colgate-Palmolive India",
        "EMAMILTD.NS": "Emami",
        "TATACONSUM.NS": "Tata Consumer Products",
        "VBLLTD.NS": "Varun Beverages",
        "UBL.NS": "United Breweries",
        "RADICO.NS": "Radico Khaitan",
        "MCDOWELL-N.NS": "United Spirits",
        "BAJAJCON.NS": "Bajaj Consumer Care",
        "GILLETTE.NS": "Gillette India",
        "PGHH.NS": "Procter & Gamble Hygiene",
        "JYOTHYLAB.NS": "Jyothy Labs",
        "ZYDUSWELL.NS": "Zydus Wellness",
        "HATSUN.NS": "Hatsun Agro Product",
        "PARAS.NS": "Paras Pharmaceuticals",
        "VENKEYS.NS": "Venky's India",
    },

    "Pharmaceuticals": {
        "SUNPHARMA.NS": "Sun Pharmaceutical",
        "DRREDDY.NS": "Dr. Reddy's Laboratories",
        "CIPLA.NS": "Cipla",
        "DIVISLAB.NS": "Divi's Laboratories",
        "AUROPHARMA.NS": "Aurobindo Pharma",
        "BIOCON.NS": "Biocon",
        "TORNTPHARM.NS": "Torrent Pharmaceuticals",
        "LUPIN.NS": "Lupin",
        "ALKEM.NS": "Alkem Laboratories",
        "GLENMARK.NS": "Glenmark Pharmaceuticals",
        "IPCALAB.NS": "IPCA Laboratories",
        "ABBOTINDIA.NS": "Abbott India",
        "PFIZER.NS": "Pfizer India",
        "GLAXO.NS": "GlaxoSmithKline Pharma",
        "SANOFI.NS": "Sanofi India",
        "NATCOPHARM.NS": "Natco Pharma",
        "AJANTPHAR.NS": "Ajanta Pharma",
        "LAURUSLABS.NS": "Laurus Labs",
        "GRANULES.NS": "Granules India",
        "SUVEN.NS": "Suven Pharmaceuticals",
        "SOLARA.NS": "Solara Active Pharma",
        "GLAND.NS": "Gland Pharma",
        "ZYDUSLIFE.NS": "Zydus Lifesciences",
        "ERIS.NS": "Eris Lifesciences",
    },

    "Automobiles": {
        "MARUTI.NS": "Maruti Suzuki India",
        "TATAMOTORS.NS": "Tata Motors",
        "M&M.NS": "Mahindra & Mahindra",
        "BAJAJ-AUTO.NS": "Bajaj Auto",
        "HEROMOTOCO.NS": "Hero MotoCorp",
        "EICHERMOT.NS": "Eicher Motors",
        "TVSMOTORS.NS": "TVS Motor Company",
        "ASHOKLEY.NS": "Ashok Leyland",
        "TVSMOTOR.NS": "TVS Motor",
        "MOTHERSON.NS": "Motherson Sumi Systems",
        "BOSCHLTD.NS": "Bosch",
        "MRF.NS": "MRF",
        "APOLLOTYRE.NS": "Apollo Tyres",
        "BALKRISIND.NS": "Balkrishna Industries",
        "CEATLTD.NS": "CEAT",
        "EXIDEIND.NS": "Exide Industries",
        "AMARAJABAT.NS": "Amara Raja Batteries",
        "MINDAIND.NS": "Minda Industries",
        "ENDURANCE.NS": "Endurance Technologies",
        "SUPRAJIT.NS": "Suprajit Engineering",
        "CRAFTSMAN.NS": "Craftsman Automation",
        "OLECTRA.NS": "Olectra Greentech",
    },

    "Oil & Gas": {
        "RELIANCE.NS": "Reliance Industries",
        "ONGC.NS": "Oil & Natural Gas Corp",
        "IOC.NS": "Indian Oil Corporation",
        "BPCL.NS": "Bharat Petroleum",
        "HPCL.NS": "Hindustan Petroleum",
        "GAIL.NS": "GAIL India",
        "OIL.NS": "Oil India",
        "PETRONET.NS": "Petronet LNG",
        "MRPL.NS": "Mangalore Refinery",
        "HINDPETRO.NS": "Hindustan Petroleum Corp",
        "CHENNPETRO.NS": "Chennai Petroleum",
        "CASTROLIND.NS": "Castrol India",
        "GULFOILLUB.NS": "Gulf Oil Lubricants",
        "TIDEWATER.NS": "Tide Water Oil",
    },

    "Metals & Mining": {
        "TATASTEEL.NS": "Tata Steel",
        "JSWSTEEL.NS": "JSW Steel",
        "HINDALCO.NS": "Hindalco Industries",
        "VEDL.NS": "Vedanta",
        "SAIL.NS": "Steel Authority of India",
        "NATIONALUM.NS": "National Aluminium",
        "NMDC.NS": "NMDC",
        "COALINDIA.NS": "Coal India",
        "JINDALSTEL.NS": "Jindal Steel & Power",
        "JSWENERGY.NS": "JSW Energy",
        "APLAPOLLO.NS": "APL Apollo Tubes",
        "RATNAMANI.NS": "Ratnamani Metals",
        "WELCORP.NS": "Welspun Corp",
        "TINPLATE.NS": "Tinplate Company",
        "MOIL.NS": "MOIL",
        "GMRINFRA.NS": "GMR Infrastructure",
        "HINDCOPPER.NS": "Hindustan Copper",
        "KMCSHIL.NS": "KMC Shil",
    },

    "Infrastructure & Construction": {
        "LARSENTOUBRO.NS": "Larsen & Toubro",
        "LT.NS": "Larsen & Toubro",
        "ULTRACEMCO.NS": "UltraTech Cement",
        "SHREECEM.NS": "Shree Cement",
        "AMBUJACEM.NS": "Ambuja Cements",
        "ACC.NS": "ACC",
        "DALMIACEME.NS": "Dalmia Bharat",
        "RAMCOCEM.NS": "Ramco Cements",
        "JKCEMENT.NS": "JK Cement",
        "HEIDELBERG.NS": "HeidelbergCement India",
        "NCC.NS": "NCC",
        "KEC.NS": "KEC International",
        "KALPATPOWR.NS": "Kalpataru Power",
        "ENGINERSIN.NS": "Engineers India",
        "RITES.NS": "RITES",
        "IRCON.NS": "IRCON International",
        "NBCC.NS": "NBCC India",
        "PNCINFRA.NS": "PNC Infratech",
        "DILIPBLDNG.NS": "Dilip Buildcon",
        "HG INFRA.NS": "H.G. Infra Engineering",
    },

    "Telecom": {
        "BHARTIARTL.NS": "Bharti Airtel",
        "IDEA.NS": "Vodafone Idea",
        "TATACOMM.NS": "Tata Communications",
        "STLTECH.NS": "Sterlite Technologies",
        "TEJAS.NS": "Tejas Networks",
        "HFCL.NS": "HFCL",
        "RITCO.NS": "RITCO Logistics",
        "RAILTEL.NS": "RailTel Corporation",
        "ITI.NS": "ITI Limited",
    },

    "Insurance": {
        "LICI.NS": "Life Insurance Corporation",
        "HDFCLIFE.NS": "HDFC Life Insurance",
        "SBILIFE.NS": "SBI Life Insurance",
        "ICICIPRULI.NS": "ICICI Prudential Life",
        "ICICIGI.NS": "ICICI Lombard General",
        "STARHEALTH.NS": "Star Health Insurance",
        "NIACL.NS": "New India Assurance",
        "GICRE.NS": "GIC Re",
        "MASFIN.NS": "MAS Financial Services",
    },

    "Power & Energy": {
        "NTPC.NS": "NTPC",
        "POWERGRID.NS": "Power Grid Corporation",
        "ADANIPOWER.NS": "Adani Power",
        "TATAPOWER.NS": "Tata Power",
        "TORNTPOWER.NS": "Torrent Power",
        "CESC.NS": "CESC",
        "NHPC.NS": "NHPC",
        "SJVN.NS": "SJVN",
        "RECLTD.NS": "REC",
        "PFC.NS": "Power Finance Corporation",
        "ADANIGREEN.NS": "Adani Green Energy",
        "GREENKO.NS": "Greenko Energy",
        "RPOWER.NS": "Reliance Power",
        "JPPOWER.NS": "Jaiprakash Power",
        "INOXWIND.NS": "Inox Wind",
        "SUZLON.NS": "Suzlon Energy",
        "ORIENTELEC.NS": "Orient Electric",
        "POLYCAB.NS": "Polycab India",
        "HAVELLS.NS": "Havells India",
        "ABB.NS": "ABB India",
        "SIEMENS.NS": "Siemens India",
        "BHEL.NS": "BHEL",
        "CGPOWER.NS": "CG Power and Industrial",
        "THERMAX.NS": "Thermax",
    },

    "Realty": {
        "DLF.NS": "DLF",
        "GODREJPROP.NS": "Godrej Properties",
        "OBEROIRLTY.NS": "Oberoi Realty",
        "PRESTIGE.NS": "Prestige Estates Projects",
        "BRIGADE.NS": "Brigade Enterprises",
        "MAHLIFE.NS": "Mahindra Lifespace",
        "SOBHA.NS": "Sobha",
        "PHOENIXLTD.NS": "Phoenix Mills",
        "SUNTECK.NS": "Sunteck Realty",
        "KOLTEPATIL.NS": "Kolte-Patil Developers",
        "ANANTRAJ.NS": "Anant Raj",
        "NESCO.NS": "NESCO",
        "IBREALEST.NS": "Indiabulls Real Estate",
        "ASHIANA.NS": "Ashiana Housing",
        "ARVIND.NS": "Arvind SmartSpaces",
    },

    "Retail & Consumer": {
        "AVENUE.NS": "Avenue Supermarts (D-Mart)",
        "TRENT.NS": "Trent",
        "SHOPERSTOP.NS": "Shoppers Stop",
        "ABFRL.NS": "Aditya Birla Fashion",
        "VMART.NS": "V-Mart Retail",
        "NYKAA.NS": "FSN E-Commerce (Nykaa)",
        "ZOMATO.NS": "Zomato",
        "SWIGGY.NS": "Swiggy",
        "MEESHO.NS": "Meesho",
        "FIRSTCRY.NS": "FirstCry",
        "TITAN.NS": "Titan Company",
        "KALYANIJP.NS": "Kalyani Forge",
        "KALYANKJIL.NS": "Kalyan Jewellers",
        "SENCO.NS": "Senco Gold",
        "PCJEWELLER.NS": "PC Jeweller",
        "CERA.NS": "Cera Sanitaryware",
    },

    "Logistics & Transportation": {
        "DELHIVERY.NS": "Delhivery",
        "BLUEDART.NS": "Blue Dart Express",
        "GATI.NS": "Gati",
        "TCI.NS": "Transport Corporation",
        "MAHLOG.NS": "Mahindra Logistics",
        "ALLCARGO.NS": "Allcargo Logistics",
        "GATEWAY.NS": "Gateway Distriparks",
        "CONCOR.NS": "Container Corporation",
        "IRCTC.NS": "IRCTC",
        "INTERGLOBE.NS": "InterGlobe Aviation (IndiGo)",
        "SPICEJET.NS": "SpiceJet",
        "AIRINDIA.NS": "Air India",
        "SCI.NS": "Shipping Corporation",
        "ESSARPORTS.NS": "Essar Ports",
        "ADANIPORTS.NS": "Adani Ports & SEZ",
        "GPPL.NS": "Gujarat Pipavav Port",
    },

    "Chemicals & Specialty": {
        "PIDILITIND.NS": "Pidilite Industries",
        "ASTRAL.NS": "Astral Poly Technik",
        "SUPREME.NS": "Supreme Industries",
        "AARTI.NS": "Aarti Industries",
        "NAVINFLUOR.NS": "Navin Fluorine International",
        "FINEORG.NS": "Fine Organic Industries",
        "SUDARSCHEM.NS": "Sudarshan Chemical",
        "VINATIORGA.NS": "Vinati Organics",
        "CLEAN.NS": "Clean Science and Technology",
        "TATACHEM.NS": "Tata Chemicals",
        "GHCL.NS": "GHCL",
        "DEEPAKNTR.NS": "Deepak Nitrite",
        "BASF.NS": "BASF India",
        "NOCIL.NS": "NOCIL",
        "ALKYLAMINE.NS": "Alkyl Amines Chemicals",
        "BALCHEMICA.NS": "Balaji Amines",
        "GALAXYSURF.NS": "Galaxy Surfactants",
        "QUESS.NS": "Quess Corp",
    },

    "Cement": {
        "ULTRACEMCO.NS": "UltraTech Cement",
        "SHREECEM.NS": "Shree Cement",
        "AMBUJACEM.NS": "Ambuja Cements",
        "ACC.NS": "ACC",
        "DALMIACEME.NS": "Dalmia Bharat",
        "RAMCOCEM.NS": "The Ramco Cements",
        "JKCEMENT.NS": "JK Cement",
        "BIRLACORPN.NS": "Birla Corporation",
        "HEIDELBERG.NS": "HeidelbergCement India",
        "JKIL.NS": "JK Infrastructure",
        "SANGHI.NS": "Sanghi Industries",
        "PRISM.NS": "Prism Johnson",
    },

    "Textiles & Apparel": {
        "PAGEIND.NS": "Page Industries",
        "RUPA.NS": "Rupa & Company",
        "LAXMIMACH.NS": "Lakshmi Machine Works",
        "ARVINDLTD.NS": "Arvind",
        "VARDHMAN.NS": "Vardhman Textiles",
        "WELSPUNIND.NS": "Welspun India",
        "TRIDENT.NS": "Trident",
        "HIMATSEIDE.NS": "Himatsingka Seide",
        "RAYMOND.NS": "Raymond",
        "MANYAVAR.NS": "Vedant Fashions (Manyavar)",
        "SAPPHIRE.NS": "Sapphire Foods India",
        "GOKEX.NS": "Gokaldas Exports",
        "KPRMILL.NS": "K.P.R. Mill",
    },

    "Hospitality & Tourism": {
        "INDHOTEL.NS": "Indian Hotels (Taj)",
        "EIH.NS": "EIH (Oberoi Hotels)",
        "LEMONTREE.NS": "Lemon Tree Hotels",
        "CHALET.NS": "Chalet Hotels",
        "MAHINDHO.NS": "Mahindra Holidays",
        "THOMASCOOK.NS": "Thomas Cook India",
        "MKTD.NS": "MakeMyTrip",
        "EASEMYTRIP.NS": "Easy Trip Planners",
        "IHCLTD.NS": "IHC",
        "TAJGVK.NS": "Taj GVK Hotels & Resorts",
    },

    "Media & Entertainment": {
        "ZEEL.NS": "Zee Entertainment",
        "SUNTVNETWORK.NS": "Sun TV Network",
        "NETWORK18.NS": "Network18 Media",
        "TV18BRDCST.NS": "TV18 Broadcast",
        "SUNTV.NS": "Sun TV",
        "DISHTV.NS": "Dish TV India",
        "TATASKY.NS": "Tata Sky",
        "PVRINOX.NS": "PVR INOX",
        "INOXLEISUR.NS": "INOX Leisure",
        "SAREGAMA.NS": "Saregama India",
        "TIPS.NS": "Tips Music",
        "NAZARA.NS": "Nazara Technologies",
    },

    "Healthcare & Diagnostics": {
        "APOLLOHOSP.NS": "Apollo Hospitals",
        "FORTIS.NS": "Fortis Healthcare",
        "MAXHEALTH.NS": "Max Healthcare Institute",
        "NARAYANHRU.NS": "Narayana Hrudayalaya",
        "METROPOLIS.NS": "Metropolis Healthcare",
        "LALPATHLAB.NS": "Dr. Lal Pathlabs",
        "THYROCARE.NS": "Thyrocare Technologies",
        "KRSNAA.NS": "Krsnaa Diagnostics",
        "VIJAYABANK.NS": "Vijaya Diagnostic Centre",
        "POLYMED.NS": "Poly Medicure",
        "SHALBY.NS": "Shalby",
        "YATHARTH.NS": "Yatharth Hospital",
        "HEALTHCARE.NS": "Healthcare Global",
    },

    "Capital Goods & Engineering": {
        "ABB.NS": "ABB India",
        "SIEMENS.NS": "Siemens India",
        "BHEL.NS": "Bharat Heavy Electricals",
        "CGPOWER.NS": "CG Power and Industrial Solutions",
        "THERMAX.NS": "Thermax",
        "CUMMINSIND.NS": "Cummins India",
        "GRINDWELL.NS": "Grindwell Norton",
        "TIMKEN.NS": "Timken India",
        "SCHAEFFLER.NS": "Schaeffler India",
        "SKF.NS": "SKF India",
        "FAG.NS": "FAG Bearings India",
        "ELGIEQUIP.NS": "Elgi Equipments",
        "KIRL.NS": "Kirloskar Brothers",
        "KIRLOSENG.NS": "Kirloskar Electric",
        "TRIVENI.NS": "Triveni Turbine",
        "SWELECTES.NS": "SW Electricals",
        "VOLTAMP.NS": "Voltamp Transformers",
        "TDPOWERSYS.NS": "TD Power Systems",
    },

    "Conglomerates": {
        "RELIANCE.NS": "Reliance Industries",
        "ADANIENT.NS": "Adani Enterprises",
        "TATAINVEST.NS": "Tata Investment Corporation",
        "BAJAJHLDNG.NS": "Bajaj Holdings",
        "GODREJIND.NS": "Godrej Industries",
        "MAHINDRA.NS": "Mahindra & Mahindra",
        "ABIRLANUVO.NS": "Aditya Birla Nuvo",
        "3MINDIA.NS": "3M India",
        "HONAUT.NS": "Honeywell Automation",
    },

    "Agri & Food Processing": {
        "UPL.NS": "UPL",
        "PI.NS": "PI Industries",
        "RALLIS.NS": "Rallis India",
        "BAYER.NS": "Bayer CropScience",
        "INSECTICID.NS": "Insecticides India",
        "DHANUKA.NS": "Dhanuka Agritech",
        "ASTEC.NS": "Astec LifeSciences",
        "COROMANDEL.NS": "Coromandel International",
        "GNFC.NS": "Gujarat Narmada Valley",
        "CHAMBALFERT.NS": "Chambal Fertilisers",
        "RCFLTD.NS": "RCF",
        "NFL.NS": "National Fertilizers",
        "ATUL.NS": "Atul",
        "GODREJAGRO.NS": "Godrej Agrovet",
        "KWALITY.NS": "Kwality",
        "HERITAGE.NS": "Heritage Foods",
        "KRBL.NS": "KRBL",
        "LT FOODS.NS": "LT Foods",
        "USHAMART.NS": "Usha Martin",
    },
}

# Flatten all stocks into a single dict for easy lookup
ALL_STOCKS = {}
for sector, stocks in NSE_STOCKS.items():
    for symbol, name in stocks.items():
        ALL_STOCKS[symbol] = {"name": name, "sector": sector}

# Featured stocks for quick access on dashboard
FEATURED_STOCKS = [
    {"symbol": "RELIANCE.NS", "name": "Reliance Industries", "sector": "Oil & Gas"},
    {"symbol": "TCS.NS", "name": "Tata Consultancy Services", "sector": "IT - Software"},
    {"symbol": "HDFCBANK.NS", "name": "HDFC Bank", "sector": "Banking - Private"},
    {"symbol": "INFY.NS", "name": "Infosys", "sector": "IT - Software"},
    {"symbol": "ICICIBANK.NS", "name": "ICICI Bank", "sector": "Banking - Private"},
    {"symbol": "HINDUNILVR.NS", "name": "Hindustan Unilever", "sector": "FMCG"},
    {"symbol": "TATAMOTORS.NS", "name": "Tata Motors", "sector": "Automobiles"},
    {"symbol": "SUNPHARMA.NS", "name": "Sun Pharmaceutical", "sector": "Pharmaceuticals"},
    {"symbol": "BAJFINANCE.NS", "name": "Bajaj Finance", "sector": "NBFC"},
    {"symbol": "ADANIENT.NS", "name": "Adani Enterprises", "sector": "Conglomerates"},
    {"symbol": "WIPRO.NS", "name": "Wipro", "sector": "IT - Software"},
    {"symbol": "MARUTI.NS", "name": "Maruti Suzuki", "sector": "Automobiles"},
]

# Index symbols for market overview
INDICES = {
    "^NSEI": "NIFTY 50",
    "^BSESN": "SENSEX",
    "^NSEBANK": "BANK NIFTY",
    "NIFTY_IT.NS": "NIFTY IT",
}

def get_all_stock_options():
    """Return list of (symbol, display_name) for selectbox"""
    options = []
    for sector, stocks in NSE_STOCKS.items():
        for symbol, name in stocks.items():
            options.append((symbol, f"{name} ({symbol.replace('.NS', '')}) — {sector}"))
    return sorted(options, key=lambda x: x[1])

def get_sectors():
    return list(NSE_STOCKS.keys())

def get_stocks_by_sector(sector):
    return NSE_STOCKS.get(sector, {})

def search_stocks(query):
    """Search stocks by name or symbol"""
    query = query.lower().strip()
    results = []
    for sector, stocks in NSE_STOCKS.items():
        for symbol, name in stocks.items():
            if query in symbol.lower() or query in name.lower():
                results.append({
                    "symbol": symbol,
                    "name": name,
                    "sector": sector
                })
    return results[:20]  # Limit to 20 results
